name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:      # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Sudarshanhingalje
          THEME: github  # you can also try themes like: "gruvbox", "vue", "monokai"

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate GitHub Profile Summary Cards"
          default_author: github_actions
